export const BOARD_SIZES = [9, 13, 19] as const;

export type BoardSize = (typeof BOARD_SIZES)[number];

export const BUSINESS_CODE = {
  SUCCESS: 0,
  VALIDATION_FAILED: 1001,
  AUTH_FAILED: 2001,
  TOKEN_INVALID: 2002,
  FORBIDDEN: 3001,
  CONFLICT: 4001,
  NOT_FOUND: 4004,
  DEFAULT_READONLY: 4005,
  RSA_DECRYPT_FAILED: 4006,
  MODEL_DISABLED: 4007,
  SERVER_ERROR: 9000,
  MASTER_KEY_INVALID: 9001,
  LLM_CALL_FAILED: 9002,
  LLM_FORMAT_INVALID: 9003,
} as const;

export const LOGOUT_CODES: number[] = [BUSINESS_CODE.TOKEN_INVALID];

export const STORAGE_PREFIX = 'go_game_';
